# This is a basic workflow to help you get started with Actions

name: GenerateCertificate

# Controls when the action will run. 
on:
  push:
    branches: [ main ]
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.SP_AZURE_CREDENTIALS}}

      - name: Install Acme Module
        uses: Azure/powershell@v1
        with:        
          inlineScript: |
            Install-Module -Name Posh-ACME -Scope CurrentUser -Force        
          azPSVersion: latest

      - name: Generate SSL Certificate
        uses: Azure/powershell@v1
        with: 
          inlineScript: 
            Set-PAServer LE_PROD
            .\scripts\letsEncrypt.ps1 -certNames ${{secrets.CERT_NAME}} -acmeContact ${{secrets.ACME_CONTACT}} -aZSubscriptionId ${{secrets.SUBSCRIPTION_ID}} -aZTenantId ${{secrets.TENANT_ID}} -aZAppUsername ${{secrets.SP_USERNAME}} -aZAppPasswordInsecure ${{secrets.SP_PASSWORD}}
          azPSVersion: latest
 
