name: Deploy KeyVault

on:  
  push:
    branches:
      - main
    paths:
      - 'bicep/keyvault.bicep'      
      - '.github/workflows/keyvault.yml'

  workflow_dispatch:
    
env:
  APIM_RESOURCE_GROUP_NAME: api-demo-rg  
  LOCATION: eastus

jobs:
  deploy_keyvault_resources:
    runs-on: ubuntu-latest 
    
    steps:
      - uses: actions/checkout@v2

      # Login to Azure
      - name: Azure Login
        uses: Azure/login@v1.1
        with:          
          creds: ${{ secrets.SP_AZURE_CREDENTIALS }}          
          enable-AzPSSession: false
      
      # Compile bicep files
      - name: Bicep Build
        uses: aliencube/bicep-build-actions@v0.1
        with:
          files: bicep/keyvault.bicep
                
      # Create resource group
      - name: Create Resource Group
        run: |
         az group create -n ${{ env.APIM_RESOURCE_GROUP_NAME }} -l ${{ env.LOCATION }}

      - name: Get SP ObjectId
        run: |
         echo az ad signed-in-user show --query objectId >> $SP_OBJECT_ID

      - name: Deploy KeyVault Resources
        id: deployapim
        uses: Azure/arm-deploy@v1.0.1
        with:        
          scope: resourcegroup          
          subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}          
          region: ${{ env.LOCATION }}        
          resourceGroupName: ${{ env.APIM_RESOURCE_GROUP_NAME }}        
          template: bicep/keyvault.json   
          parameters: principalAdminObjectId=${{ secrets.ADMIN_VAULT_OBJECT_ID }} vaultName=${{ secrets.VAULT_NAME }} spIdentity=${{ env.SP_OBJECT_ID }}
          deploymentMode: Incremental      