name: Test-Env

on:  
 push:
   branches:
     - features/deploywebapp

jobs:
  compile_bicep:
    runs-on: ubuntu-latest 

    steps:
      - uses: actions/checkout@v2
      
      # Compile bicep files
      - name: Bicep Build
        uses: aliencube/bicep-build-actions@v0.1
        with:
          files: bicep/deploy.bicep bicep/onpremise.bicep

      # Deploy ARM Template
      - name: Publish ARM Template
        uses: actions/upload-artifact@v2.2.2
        with:            
          path: |
            bicep/deploy.json
            bicep/onpremise.json

  deploy_dev:
    needs: compile_bicep
    runs-on: ubuntu-latest   

    environment:
      name: HUGO

    steps:      
      - name: Azure Login
        uses: Azure/login@v1.1
        with:          
          creds: ${{ secrets.SP_AZURE_CREDENTIALS }}          
          enable-AzPSSession: false

      # Create resource group
      - name: Create Resource Group
        run: |
         az group create -n ${{ secrets.APIM_RESOURCE_GROUP_NAME }} -l ${{ secrets.LOCATION }}          